config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root controller: :restaurants, action: :index

  namespace :api do
    namespace :v0 do
      resources :hello, only: [:index], constraints: { format: 'json' }
    end
  end

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :menus, only: [:show, :index, :create, :new]
  end

  namespace 'owners' do
    resources :restaurants, only: [:index, :show, :create, :new] do
      resources :menus, only: [:show, :index, :create, :new, :update, :edit, :destroy] do
        resources :dishes, only: [:new, :create, :show, :index]
      end
    end
  end

  get '/add_to_cart/:dish_id/:restaurant_id', to: 'carts#add_to_cart', as: 'add_to_cart'
  get '/cart', to: 'carts#checkout', as: 'checkout'
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  has_many :dishes

  validates_presence_of :name
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.where(restaurant_id: params[:restaurant_id])
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/owners/menus_controller.rb
class Owners::MenusController < ApplicationController
  def new
    @menu = Menu.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @menu = Menu.new(name: params[:menu][:name], restaurant_id: params[:restaurant_id])
    if @menu.save
      redirect_to owners_restaurant_path(params[:restaurant_id])
      flash[:notice] = "Menu added"
    else
      redirect_to "new"
    end
  end

  def edit
    @menu = Menu.find(params[:id])
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def update
    menu = Menu.find(params[:id])
    menu.name = menu_params[:name]
    menu.save
    redirect_to owners_restaurant_path(params[:restaurant_id])
    flash[:notice] = "Menu updated"
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to owners_restaurant_path(params[:restaurant_id])
    flash[:notice] = "Menu deleted"
  end

  private

  def menu_params
    params.require(:menu).permit(:name)
  end
end

app/views/menus/_dish_row.html.haml
.well
  .row
    .col-cs-8
      %h4= dish.name
    .col-xs-4
      = form_for order_item, remote: true do |t|
        %h4.text-right
          Dish Price:
          %span{:style => "color: green"}= number_to_currency product.price
        .input-group
          =f.number_field :quantity, value: 1, class: "form-control", min: 1
            .input-group-btn
              = f.hidden_field :dish_id, value: dish.id
              = f.submit "Add to Cart", class: "btn btn-primary"

app/views/menus/index.html.haml
%h1 #{@restaurant.name} menus
- @menus.each do |menu|
  %p= menu.name
  %ul
  - menu.dishes.each do |dish|
    %li= dish.name
    %li= dish.description
    %li= dish.price
    %li= link_to "Add #{dish.name} to cart", add_to_cart_path(dish, @restaurant)
    = flash[:notice]

app/views/menus/new.html.haml
%h2 New Menu Form
= form_for([@user, @restaurant, @menu]) do |f|
  .field
    = f.label :name, "Menu Name"
    %br/
    = f.text_field :name, autofocus: true
  .actions
    = f.submit "Create"
    %p
      = flash[:notice]

app/views/menus/show.html.haml
%h1 #{@restaurant.name} menus
- @menus.each do |menu|
  %p= menu.name
  %ul
  - menu.dishes.each do |dish|
    %li= dish.name
    %li= dish.description
    %li= dish.price
    =render "dish_row", dish: dish, order_item: @order_item