config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root controller: :restaurants, action: :index

  namespace :api do
    namespace :v0 do
      resources :hello, only: [:index], constraints: { format: 'json' }
    end
  end

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :menus, only: [:show, :index, :create, :new]
  end

  namespace 'owners' do
    resources :restaurants, only: [:index, :show, :create, :new] do
      resources :menus, only: [:show, :index, :create, :new, :update, :edit, :destroy] do
        resources :dishes, only: [:new, :create, :show, :index]
      end
    end
  end

  get '/add_to_cart/:dish_id/:restaurant_id', to: 'carts#add_to_cart', as: 'add_to_cart'
  get '/cart', to: 'carts#checkout', as: 'checkout'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :rest_category
  belongs_to :user

  validates_presence_of :name,
                        :address,
                        :city,
                        :province,
                        :country

  geocoded_by :full_address, latitude: :latitude, longitude: :longitude
  after_validation  :geocode, if:  :address_city_province_country_present? || :address_city_province_country_changed?

  def full_address
    [address, city, province, country].compact.join(', ')
  end

  def address_city_province_country_changed?
    address_changed? || city_changed? || province_changed? || country_changed?
  end

  def address_city_province_country_present?
    address.present? && city.present? && province.present? && country.present?
  end

end

app/controllers/owners/restaurants_controller.rb
class Owners::RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.where(user_id: current_user.id)
  end

  def show
    @restaurant_id = params[:id]
    @restaurant = Restaurant.find(params[:id])
    @menus = Menu.where(restaurant_id: @restaurant.id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    if params[:category].present? == true
      cat_chosen = params[:category][:id]
      @restaurants = Restaurant.where(rest_category_id: cat_chosen)
    else
      @restaurants = Restaurant.all
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
    @categories = RestCategory.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to root_path
      flash[:notice] = 'Your restaurant has been sucessfully registered!'
    else
      render 'new'
    end
  end

  private

  def restaurant_params
    params.require(:restaurant)
          .permit(:name,
                  :address,
                  :city,
                  :province,
                  :country,
                  :rest_category_id)
  end
end

app/views/restaurants/index.html.haml
- if user_signed_in?
  = link_to "Are you a restaurant owner? Click to register your restaurant", new_restaurant_path
- if user_signed_in? && current_user.restaurant_owner?
  = link_to "View My Restaurant Page", owners_restaurants_path(current_user)
%div
  = form_tag(root_path, method: 'get') do
    = label_tag(:category, 'Filter by category: ')
    = collection_select(:category, :id, RestCategory.all, :id, :name)
    = submit_tag('Filter')

%div
  %ul
    - @restaurants.each do |restaurant|
      %li= link_to (restaurant.name), restaurant_path(restaurant)
      %ul
        %li Address: #{restaurant.address}
        %li Email: #{restaurant.email}
        %li Phone: #{restaurant.phone}
#map{ style: "width: 100%; height: 400px;" }

app/views/restaurants/new.html.haml
%h2 Restaurant Registration Form
= form_for @restaurant  do |f|
  - if @restaurant.errors.any?
    - @restaurant.errors.full_messages.each do |message|
      = message
  .field
    = f.label :name, "Restaurant Name"
    %br/
    = f.text_field :name, autofocus: true
  .field
    = f.label :address, "Address"
    %br/
    = f.text_field :address
  .field
    = f.label :city, "City"
    %br/
    = f.text_field :city
  .field
    = f.label :province, "Province"
    %br/
    = f.text_field :province
  .field
    = f.label :country, "Country"
    %br/
    = f.text_field :country
  .field
    = f.label :rest_category_id, "Restaurant Category"
    %br/
    = f.collection_select(:rest_category_id, @categories, :id, :name)
  .actions
    = f.submit "Submit"
    %p
      = flash[:notice]

app/views/restaurants/show.html.haml
%h1= @restaurant.name
%ul
  %li
    Address:
    = @restaurant.address
  %li Email: #{@restaurant.email}
  %li Phone: #{@restaurant.phone}
  = @restaurant.description
  = link_to "Full menu", restaurant_menus_path(@restaurant)